# Generated by Django 2.0.5 on 2018-05-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
