# Generated by Django 2.0.5 on 2018-05-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0002_remove_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PUBMEDID',
            field=models.IntegerField(default=0),
        ),
    ]
