# Generated by Django 2.0.5 on 2018-05-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0004_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='JOURNAL',
            field=models.CharField(default='', max_length=100),
        ),
    ]
