# Generated by Django 2.0.5 on 2018-05-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0005_post_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='LINK',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='STUDY',
            field=models.CharField(default='', max_length=400),
        ),
    ]
