# Generated by Django 2.0.5 on 2018-05-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0006_auto_20180515_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='DISEASE_TRAIT',
            field=models.CharField(default='', max_length=200),
        ),
    ]
