# Generated by Django 2.0.5 on 2018-05-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0007_post_disease_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='CHR_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='CHR_POS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='RSID_CURRENT',
            field=models.IntegerField(default=0),
        ),
    ]
