# Generated by Django 2.0.5 on 2018-05-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0009_post_p_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PVALUE_MLOG',
            field=models.FloatField(default=0),
        ),
    ]
