# Generated by Django 2.0.5 on 2018-05-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0010_post_pvalue_mlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
