# Generated by Django 2.0.5 on 2018-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0014_snp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pubmedid', models.IntegerField()),
                ('Journal', models.IntegerField()),
                ('Title', models.IntegerField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
