# Generated by Django 2.0.5 on 2018-05-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0020_snp2phenotype2ref_pvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='snp2phenotype2ref',
            name='neglog10pvalue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='snp2phenotype2ref',
            name='pvalue',
            field=models.FloatField(default=0),
        ),
    ]
